### PR TITLE
VTCCA-3166: added support for searching by appointed from and to dates

### PR DESCRIPTION
**Pull request by habeeb01**

### CODE REVIEW

**Comment by PeterPerhac** [comment]
code looks good, I just don't see any tests

**Comment by habeeb01** [comment]
@PeterPerhac I updated existing test for get client properties to include the newly added fields (I didn't do "git add ." 🤦‍♂️ ). It should be there now

**Comment by PeterPerhac** [comment]
thank you 👍

**Comment by reddy-yattapu** [comment]
👍

**Pull request merged**
